language: 
  - node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
services:
  - postgresql
  
before_install:
  - npm update
install:
  - npm install
script:
  - npm test

before_script:
  - psql -c 'create database olympians_test;' -U postgres
  - knex migrate:latest --env test

deploy:
  provider: heroku
  api_key:
    secure: 764a9624-2924-4824-a22e-cbaa43515b17
  app:
    dev: staging-olympians
    master: olympians
  run:
    - knex migrate:latest
